### PR TITLE
Implemented the token refresh procedure

### PR DESCRIPTION
**Pull request by justedro**
# Description of change
Wootric somehow changed its token expiration time, and our integration in Stitch broke as it's now unable to finish sync in 2 hours. 

I've implemented the access token refreshing and updated outdated dependencies.
 https://docs.wootric.com/api/#authentication

# Manual QA steps
 - Run the tap locally, check that it works well and refreshes the token in time
 
# Risks
 - Updated deps
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by justedro** [comment]
Hi @dmosorast,
please take a look at this PR

**Comment by dmosorast** [comment]
@JustEdro Cool, this looks good. I don't have an account to test it with, can you post some redacted log snippets (no data please) of it running that includes the "Authenticating" log line?

**Comment by justedro** [comment]
@dmosorast here it is
I've set the `refresh_after = 20` so the integration should re-authorize every 20 seconds:
`refresh_after = 20  # int(data["expires_in"]) - 60  # refresh in one minute in advance`

The log: https://gist.github.com/JustEdro/a24154a91a5197b3ef9abf6be0136243

**Review by dmosorast — APPROVED** [review]
Great! Thank you. I'm good to merge and release this :+1:

**Comment by justedro** [comment]
Cool, thank you, @dmosorast 
Could you tell when exactly this should deliver to Stitch production?

**Comment by dmosorast** [comment]
@JustEdro In about 5 to 10 minutes. You should see it on your next sync. It'll be version `0.5.1` since I robotically bumped the version after merge and didn't realize you had already bumped it to `0.5.0` 😅

**Pull request merged**
