### PR TITLE
Added sliding window and multiplier variables

### PR DESCRIPTION
**Pull request by lantern-eight**
# Description of change

Made the sliding window and the sliding window multiplier a variable that can be passed in from the config instead of hard coded. Still retains orignal hard coded values as default values if they are not passed in.

Should be no breaking changes.

# Manual QA steps

 Certified works for us
 
# Risks
 - None, uses original hardcoded values as defaults where no variable is passed in (i.e. no breaking changes)
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @canada11, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @canada11!

Thank you for signing the Singer Contribution License Agreement.

**Comment by aidan-melen** [comment]
@cmerrick Do you know why the circleci build is stuck?

**Comment by aidan-melen** [comment]
poke @cmerrick  what is the deal with the circleci build?

**Comment by aidan-melen** [comment]
anyone?

image

**Comment by lantern-eight** [comment]
It's not meant to be 😜

**Pull request closed without merging**
